export const TOPIC_KEYWORDS = [
  "ai",
  "agent",
  "agents",
  "llm",
  "mcp",
  "model-context-protocol",
  "rag",
  "openai",
  "claude",
  "codex",
  "cursor",
  "gemini",
  "automation",
  "workflow",
  "hooks",
  "skills",
  "devtools",
  "developer-tools",
  "prompt-engineering",
  "local-ai"
];

export const TEXT_KEYWORDS = [
  "ai agent",
  "agent framework",
  "autonomous agent",
  "llm",
  "large language model",
  "mcp",
  "model context protocol",
  "claude code",
  "codex",
  "cursor",
  "opencode",
  "gemini",
  "rag",
  "retrieval augmented generation",
  "prompt engineering",
  "developer automation",
  "workflow automation",
  "hooks",
  "skills",
  "local ai"
];
